name: Run e2e tests
description: Runs e2e tests

runs:
  using: 'composite'

  steps:
    - name: Cypress run X Components
      uses: cypress-io/github-action@v5
      with:
        install: false
        browser: chrome
        start: pnpm --filter @empathyco/x-components run preview
        project: packages/x-components

    - name: Cypress run X Components component
      uses: cypress-io/github-action@v5
      with:
        install: false
        browser: chrome
        start: pnpm --filter @empathyco/x-components run serve
        project: packages/x-components
        component: true

    - name: Cypress run React Wrapper
      uses: cypress-io/github-action@v5
      with:
        install: false
        browser: chrome
        start: pnpm --filter @empathyco/x-react-wrapper run serve
        project: packages/x-components
